project = "lcars_plugin_apt"
version = 1
author = "Frank Holler"

[setup]
requirements = ["pyyaml"]

[setup.run]
apt = "%git%/lcars_plugin_apt/run/apt.py %base%"

[[systemd]]
name = "lcars-apt.service"
start = false
content = '''
[Unit]
Description=Taegliche Pruefung auf Updates 

[Service]
WorkingDirectory=%base%
ExecStart=%python% %git%/lcars_plugin_apt/run/run.py %base%
'''

[[systemd]]
name = "lcars-apt.timer"
content = '''
[Unit]
Description=Taegliche Pruefung auf Updates 

[Timer]
OnCalendar=*-*-* 03,09,15,21:00:00
RandomizedDelaySec=1h
Persistent=true

[Install]
WantedBy=timers.target
'''